# Generated by Django 5.2.6 on 2025-10-10 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalHerb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('character', models.TextField()),
                ('living_specification', models.TextField()),
                ('chemical_composition', models.TextField()),
                ('raw_material_for_medicine', models.TextField()),
                ('usage', models.TextField()),
                ('natural_source', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
