# Generated by Django 5.2.6 on 2025-10-11 15:20

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_medicalherb_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalherb',
            name='character',
        ),
        migrations.RemoveField(
            model_name='medicalherb',
            name='chemical_composition',
        ),
        migrations.RemoveField(
            model_name='medicalherb',
            name='living_specification',
        ),
        migrations.RemoveField(
            model_name='medicalherb',
            name='natural_source',
        ),
        migrations.RemoveField(
            model_name='medicalherb',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='medicalherb',
            name='raw_material_for_medicine',
        ),
        migrations.RemoveField(
            model_name='medicalherb',
            name='usage',
        ),
        migrations.AddField(
            model_name='medicalherb',
            name='content',
            field=ckeditor.fields.RichTextField(default=1),
            preserve_default=False,
        ),
    ]
