# Generated by Django 5.2.6 on 2025-10-11 15:32

import apps.core.fields
import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_medicalherb_character_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalherb',
            name='photo',
            field=apps.core.fields.AdvanceThumbnailField(blank=True, help_text='Photo of the medical herb', null=True, upload_to='herbs/'),
        ),
        migrations.AlterField(
            model_name='medicalherb',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
