# Generated by Django 5.2.6 on 2025-10-11 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_medicalherb_photo_alter_medicalherb_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalherb',
            name='name_latin',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
